### ISSUE TITLE
The code here is not completed yet?

### ISSUE THREAD

**Issue by jacksmith3888** [emmyyusufu/codestack-gatsby-blog#1]
Hi,
I saw your post on medium, so i came here to have a look.
many thanks to your post ,but some code listed on the post in medium didnt appear here, is there any posibilities for you to upload the full code, especially the graphql part

Thank you

**Comment by emmyyusufu** [comment]
I'm so sorry for the late response. I have been unavailable since then. I've pushed the full code. Thanks.
